default_platform(:ios)

platform :ios do
  desc "appstore 업로드"
  lane :release do |version:|
    api_key =
      app_store_connect_api_key(
        key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
        is_key_content_base64: true,
        issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
        key_content: ENV["APP_STORE_CONNECT_KEY_CONTENT"],
        in_house: false
      )
        
   create_keychain(
        name: ENV["KEYCHAIN_NAME"],
        password: ENV["KEYCHAIN_PASSWORD"],
        timeout: 1800,
        default_keychain: true,
        unlock: true,
        lock_when_sleeps: false
    )

    latest = latest_testflight_build_number(
      app_identifier: "com.est.ico",
      version: version
    )

    increment_build_number(
      build_number: latest + 1
    )

    match(
      type: "appstore",
      keychain_name: ENV["KEYCHAIN_NAME"],
      keychain_password: ENV["KEYCHAIN_PASSWORD"],
      readonly: true
    )

    build_app(
      scheme: "iCo",
      clean: true,
      export_method: "app-store",
      export_options: {
        signingStyle: "manual",
        provisioningProfiles: {
          "com.est.ico" => "match AppStore com.est.ico",
          "com.est.ico.widget" => "match AppStore com.est.ico.widget"
        }
      }
    )

    upload_to_app_store(
      app_version: version,
      submit_for_review: false,
      force: true,
      automatic_release: false,
      skip_screenshots: true,
      skip_metadata: true,
      precheck_include_in_app_purchases: false,
      submission_information: { add_id_info_uses_idfa: false }
    )
  end

  desc "빌드하고 TestFlight에 업로드"
  lane :testflight do

    api_key =
        app_store_connect_api_key(
          key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
          is_key_content_base64: true,
          issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
          key_content: ENV["APP_STORE_CONNECT_KEY_CONTENT"],
          in_house: false
        )
        
   create_keychain(
        name: ENV["KEYCHAIN_NAME"],
        password: ENV["KEYCHAIN_PASSWORD"],
        timeout: 1800,
        default_keychain: true,
        unlock: true,
        lock_when_sleeps: false
    )

    increment_build_number    

    match(
      type: "appstore",
       keychain_name: ENV["KEYCHAIN_NAME"],
       keychain_password: ENV["KEYCHAIN_PASSWORD"],
      readonly: true
    )

    build_app(
      scheme: "iCo",
      clean: true,
      export_method: "app-store",
      export_options: {
        signingStyle: "manual",
        provisioningProfiles: {
          "com.est.ico" => "match AppStore com.est.ico",
          "com.est.ico.widget" => "match AppStore com.est.ico.widget"
        }
      }
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: false,
      submit_beta_review: false,
      distribute_external: false,
      changelog: "새로운 기능 및 버그 수정"
    )
  end
end

