name: iOS CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest
    
    # Xcode 빌드 환경 변수
    env:
      project: ${{ 'AIProject/iCo.xcodeproj' }}
      scheme: ${{ 'iCoTests' }}
      platform: ${{ 'iOS Simulator' }}
      device: ${{ 'iPhone 16 Pro' }}
      os: ${{ '18.6' }}

    steps:
      
      # 레파지토리 체크인
      - name: Checkout
        uses: actions/checkout@v4
  
      # XCConfig / GoogleService 등의 파일을 클론
      - name: Clone Secret file
        uses: actions/checkout@v4
        with:
          repository: ESTiOSAI/Secrets
          path: temp/
          token: ${{ secrets.SECRET_TOKEN }}
      
      # 가져온 파일 이동
      - name: Move config
        run: |
          mv temp/XCConfig/Secrets.xcconfig AIProject/iCo/App/Resource/
          mv temp/GoogleServices/GoogleService-Info.plist AIProject/iCo/App/Resource/
      # SPM Dependency 캐싱
      - name: Cache Swift Packages
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Developer/Xcode/DerivedData/*/SourcePackages
          # .build
          # ~/.swiftpm
          # ~/Library/Caches/org.swift.swiftpm
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-
      # SPM Resolve
      - name: Resolve Packages
        run: |
          cd AIProject
          xcodebuild -resolvePackageDependencies -scheme "$scheme"
      # 모듈 캐싱
      # - name: Cache DerivedData
      #   uses: actions/cache@v4
      #   with:
      #     path: ~/Library/Developer/Xcode/DerivedData
      #     key: ${{ runner.os }}-build-${{ hashFiles('**/*.swift') }}
      #     restore-keys: |
      #       ${{ runner.os }}-build-
          
      - name: Build
        run: |
          xcodebuild build-for-testing \
            -project "$project" \
            -scheme "$scheme" \
            -destination "platform=$platform,name=$device,OS=18.6"
            
      - name: Test
        run: |
          xcodebuild test-without-building \
            -project "$project" \
            -scheme "$scheme" \
            -destination "platform=$platform,name=$device,OS=18.6"
